name: dart_database
version: 0.0.2
author: Maxim Savin <soulman.is.good@gmail.com>
description: Embeded database written on Dart
homepage: https://github.com/soulman-is-good/dart-database
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  test: ^1.5.3
  meta: ^1.1.7
